### PR TITLE
Add simple compile-time txpower control and boost/neg-boost. [...]

### PR DESCRIPTION
**Pull request by yagoplx**
Making this go all the way to iw or iwconfig is way outsidet of my capabilities but if you want to give it a try, go ahead. Right now this is enough for my needs.

All the changes here have been throughly tested.

Added LD optimizations.
Added DKMS to use threaded compile
Add simple compile-time txpower control and boost/neg-boost and reference to it in readme.
Fixed readme typos on HT-capabs and other improvements

### CODE REVIEW

**Comment by lwfinger** [comment]
I do not like hard-coding the "-j" part to make. It is fine when the driver builds; however, it is a PITA when there are warnings or errors as they scroll off the screen. In addition, the recommended value is not nproc, but 2*nproc+1. That will keep all processors busy as long as you have sufficient memory. IF you get into swapping, then using multiple jobs will slow the build.

**Comment by yagoplx** [comment]
Odd. Con Kolivas recommends using -j$(nproc) and not any higher. But that may be restricted to what he sees in his CPU scheduler.

I can change it, but do note that people using DKMS are usually not debugging the driver, rather, they are updating their kernel. It is important that this process is not too slow, at least how I see it. If you need to have nice warnings. just run make all on the source folder instead.

**Comment by lwfinger** [comment]
I build many, many kernels. My main laptop has 4 processors. Using 'make -j4' does not keep all CPUs busy for these 20 minute builds. I tested various numbers and -j9 used the least elapsed time. On a 2 minute build, it does not make much difference

**Comment by yagoplx** [comment]
My i3 also has four cores. Here are my results:
-j4 -> real	0m39,729s  
-j9 -> real	0m38,470s
no -j -> real	1m22,159s

Obviously 2*nproc+1 will usually lead to a performance increase because more stuff will be loaded in memory. It is not ideal if you want to do stuff in the foreground, as it may starve other processes of memory and CPU time. Really depends on your workflow.

It's really whatever in this driver's case, -j nproc fits the role well in dkms, but only very impatient people will really notice anything.

I don't think a rule for thread amount actually exists.

**Pull request merged**
